## Dataset

In [39]:
import pandas as pd
import numpy as np

data = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1],
}

In [40]:
AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [41]:
X = AND.drop("y",axis = 1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [42]:
y = AND['y']
#y = y.to_frame()
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

## Bias

In [43]:
bias = -np.ones(len(X))
bias

array([-1., -1., -1., -1.])

In [44]:
bias = -np.ones((len(X),1))
bias

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [45]:
x_with_bias = np.c_[X, bias] # concactination
bias

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

## Perceptron Class

In [46]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z > 0 , 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # concactination
    print(f"X_with_bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch: {epoch}")
      y_hat = self.activationFunction(X_with_bias, self.weights)
      print(f"predicted value: \n{y_hat}")
      error = self.y - y_hat
      print(f"error: \n{error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"updated weights: \n{self.weights}")
      print("#############\n")

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activationFunction(X_with_bias, self.weights)

## Train

In [47]:
model = Perceptron(eta = 0.5, epochs = 10)
model.fit(X,y)

self.weights: [-2.74867456e-05  1.77381941e-04  3.66038360e-05]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value:
[0 1 0 1]
error:
0    0
1   -1
2    0
3    0
Name: y, dtype: int64
updated weights:
[-2.74867456e-05 -4.99822618e-01  5.00036604e-01]
#############

for epoch: 1
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[4.99972513e-01 1.77381941e-04 3.66038360e-05]
#############

for epoch: 2
predicted value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-2.74867456e-05 -4.99822618e-01  1.00003660e+00]
#############

for epoch: 3
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[4.99972513e-01 1.77381941e-04 5.00036604e-01]
#############

for epoch: 4
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[4.99972513e-01 1.77381941e-04 5.00036604e-01]
#############

for epoch: 5
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[4.99972513e-01 1.77381941e-04 5.00036604e-01]
#############

for epoch: 6
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[4.99972513e-01 1.77381941e-04 5.00036604e-01]
#############

for epoch: 7
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[4.99972513e-01 1.77381941e-04 5.00036604e-01]
#############

for epoch: 8
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[4.99972513e-01 1.77381941e-04 5.00036604e-01]
#############

for epoch: 9
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[4.99972513e-01 1.77381941e-04 5.00036604e-01]
#############

## Prediction

In [49]:
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [50]:
model.predict(X)

array([0, 0, 0, 1])